micronaut:
  health:
    monitor:
      enabled: false
  application:
    name: micronaut-graal
---
datasources:
  default:
    #url: "jdbc:postgresql:${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=${DB_USER}&password=${DB_PASSWORD}"
    url: "${DB_URL}"
    driverClassName: "org.mariadb.jdbc.Driver"
    dialect: MYSQL
---
endpoints:
  all:
    path: "/endpoints"
  info:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false